
import React, { useState, useEffect } from 'react';
import { Card, Button, LoadingOverlay } from '../../components/UI';
import { generateAgreementContent } from '../../services/agreementService';
import { generateUSATToken } from '../../services/tokenService';

interface Props {
  user: any;
  navigate: (v: string) => void;
  notify: (t: 'success' | 'error', m: string) => void;
}

const SignAgreement: React.FC<Props> = ({ user, navigate, notify }) => {
  const [agreement, setAgreement] = useState<any>(null);
  const [acks, setAcks] = useState({
    read: false,
    temporary: false,
    vacate: false,
    electronic: false
  });
  const [isSigning, setIsSigning] = useState(false);
  const [signatureType, setSignatureType] = useState<'type' | 'draw'>('type');
  const [typedName, setTypedName] = useState(user?.user_name || '');

  useEffect(() => {
    // Simulated guest/stay data fetching
    const stayData = {
      guestName: user?.user_name || 'Valued Guest',
      propertyAddress: '123 Ocean Drive, Miami, FL',
      checkoutDate: '2024-10-28',
      state: 'FL'
    };
    setAgreement(generateAgreementContent('FL', stayData));
  }, [user]);

  const handleSign = async () => {
    if (!Object.values(acks).every(v => v)) {
      notify('error', 'Please acknowledge all legal disclaimers to proceed.');
      return;
    }

    setIsSigning(true);
    // Simulate API call to record signature and issue token
    setTimeout(() => {
      setIsSigning(false);
      const token = generateUSATToken({
        guestName: user?.user_name,
        propertyAddress: '123 Ocean Drive, Miami, FL',
        checkoutDate: '2024-10-28'
      });
      notify('success', 'Agreement signed and USAT token issued!');
      navigate('guest-dashboard');
    }, 2000);
  };

  if (!agreement) return <LoadingOverlay message="Assembling agreement..." />;

  return (
    <div className="max-w-6xl mx-auto py-12 px-4">
      {/* Back Button */}
      <button onClick={() => navigate('guest-dashboard')} className="flex items-center gap-2 text-gray-500 hover:text-white mb-8 font-bold text-sm uppercase tracking-widest transition-colors">
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 19l-7-7 7-7"></path></svg>
        Back to Dashboard
      </button>

      <div className="flex flex-col lg:flex-row gap-12">
        {isSigning && <LoadingOverlay message="Finalizing signature..." />}
        
        {/* Left: Document View */}
        <div className="lg:w-3/5 space-y-6">
          <Card className="p-0 border-gray-800 bg-[#0d1117]/85 backdrop-blur-xl shadow-2xl">
            <div className="p-12 space-y-10 max-h-[80vh] overflow-y-auto no-scrollbar scroll-smooth">
              <div className="text-center pb-8 border-b border-gray-800">
                 <h1 className="text-2xl font-black text-white tracking-tighter mb-2">{agreement.title}</h1>
                 <p className="text-[10px] text-gray-500 font-bold uppercase tracking-widest">Document ID: {agreement.id}</p>
              </div>

              {agreement.clauses.map((clause: any, i: number) => (
                <section key={clause.id} className="space-y-4">
                  <h2 className="text-xs font-black text-blue-500 uppercase tracking-widest">{i + 1}. {clause.name}</h2>
                  <p className="text-gray-300 leading-relaxed text-sm">{clause.text}</p>
                  {clause.statute && <p className="text-[10px] text-gray-600 italic">Reference: {clause.statute}</p>}
                </section>
              ))}

              <div className="pt-12 border-t border-gray-800">
                 <p className="text-xs text-gray-500 italic text-center">This document is a legally binding revocable license generated by DocuStay AI.</p>
              </div>
            </div>
          </Card>
        </div>

        {/* Right: Signature Actions */}
        <div className="lg:w-2/5 space-y-8">
          <h2 className="text-3xl font-black text-white tracking-tighter">Sign & Confirm</h2>
          
          <Card className="p-8 space-y-6 border-blue-500/20 bg-blue-500/5">
             <h3 className="text-sm font-black text-gray-400 uppercase tracking-widest">Acknowledgments</h3>
             <div className="space-y-4">
                {[
                  { id: 'read', label: 'I have read the entire agreement' },
                  { id: 'temporary', label: 'I acknowledge my stay is temporary' },
                  { id: 'vacate', label: 'I agree to vacate on the checkout date' },
                  { id: 'electronic', label: 'I consent to electronic signature' }
                ].map(ack => (
                  <label key={ack.id} className="flex items-center gap-4 cursor-pointer group">
                    <input 
                      type="checkbox" 
                      checked={(acks as any)[ack.id]} 
                      onChange={e => setAcks({...acks, [ack.id]: e.target.checked})}
                      className="w-5 h-5 rounded border-gray-700 bg-gray-800 text-blue-600 focus:ring-blue-500"
                    />
                    <span className="text-sm text-gray-400 group-hover:text-gray-300 transition-colors font-medium">{ack.label}</span>
                  </label>
                ))}
             </div>
          </Card>

          <Card className="p-8 space-y-8 border-gray-800">
            <div className="flex gap-4 border-b border-gray-800">
               <button onClick={() => setSignatureType('type')} className={`pb-4 text-xs font-black uppercase tracking-widest border-b-2 transition-all ${signatureType === 'type' ? 'text-blue-500 border-blue-500' : 'text-gray-500 border-transparent'}`}>Type Signature</button>
               <button onClick={() => setSignatureType('draw')} className={`pb-4 text-xs font-black uppercase tracking-widest border-b-2 transition-all ${signatureType === 'draw' ? 'text-blue-500 border-blue-500' : 'text-gray-500 border-transparent'}`}>Draw Signature</button>
            </div>

            {signatureType === 'type' ? (
              <div className="space-y-4">
                 <input 
                   type="text" 
                   value={typedName}
                   onChange={e => setTypedName(e.target.value)}
                   className="w-full bg-transparent border-b-2 border-gray-800 text-4xl font-serif text-white italic outline-none focus:border-blue-500 transition-all py-4 placeholder-gray-800"
                   placeholder="Full Name"
                 />
                 <p className="text-[10px] text-gray-500 uppercase font-black">Digital Seal of Authenticity will be applied</p>
              </div>
            ) : (
              <div className="h-48 w-full bg-gray-900 border-2 border-dashed border-gray-800 rounded-2xl flex items-center justify-center group cursor-crosshair">
                 <span className="text-gray-600 font-bold text-sm group-hover:text-gray-400 transition-colors">Sign here with your pointer or finger</span>
              </div>
            )}

            <Button variant="primary" className="w-full py-5 text-xl font-black shadow-blue-600/30" onClick={handleSign}>
              {isSigning ? 'Executing Agreement...' : 'Sign & Complete Registration'}
            </Button>
          </Card>

          <div className="flex items-center gap-3 justify-center text-[10px] text-gray-600 font-black uppercase tracking-widest">
             <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"></path></svg>
             256-Bit Cryptographic Compliance
          </div>
        </div>
      </div>
    </div>
  );
};

export default SignAgreement;
